const products = [
  {
    id: 1,
    name: "Forest honey",
    category: "Honey",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 20.99,
    newPrice: 18.99,
    onSale: true,
    image: "https://imgtr.ee/images/2023/04/24/8bwbl.jpg",
  },
  {
    id: 2,
    name: "Honey candles",
    category: "Candles",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 10.99,
    newPrice: 8.99,
    onSale: false,
    image: "/images/candle.jpg",
  },
  {
    id: 3,
    name: "Forest Honeycomb",
    category: "Other",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 52.39,
    newPrice: 48.11,
    onSale: false,
    image: "/images/honeycomb.jpg",
  },
  {
    id: 4,
    name: "Pollen 100g",
    category: "Pollen",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 30.99,
    newPrice: 28.99,
    onSale: false,
    image: "/images/pollen.jpg",
  },
  {
    id: 5,
    name: "Mead",
    category: "Mead",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 140.69,
    newPrice: 99.99,
    onSale: true,
    image: "/images/mead.jpg",
  },
  {
    id: 6,
    name: "Royal milk",
    category: "Other",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 72.12,
    newPrice: 69.44,
    onSale: false,
    image: "/images/royal-milk.png",
  },
  {
    id: 7,
    name: "Honey soap",
    category: "Cosmetics",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 8.12,
    newPrice: 7.44,
    onSale: false,
    image: "/images/soap.jpg",
  },
  {
    id: 8,
    name: "Eucalyptus honey",
    category: "Honey",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 20.22,
    newPrice: 18.98,
    onSale: false,
    image: "/images/honey-in-jar2.jpg",
  },
  {
    id: 9,
    name: "Eucalyptus honeycomb",
    category: "Other",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 43.62,
    newPrice: 38.52,
    onSale: false,
    image: "/images/honeycomb2.jpg",
  },
  {
    id: 10,
    name: "Bee venom",
    category: "Bee venom",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 31.51,
    newPrice: 28.81,
    onSale: true,
    image: "/images/bee-venom.jpg",
  },
  {
    id: 11,
    name: "Orange blossom honey",
    category: "Honey",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 24.11,
    newPrice: 20.67,
    onSale: false,
    image: "/images/honey-in-jar3.jpg",
  },
  {
    id: 12,
    name: "Manuka honey",
    category: "Honey",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 13.87,
    newPrice: 10.54,
    onSale: false,
    image: "/images/honey-in-jar4.jpg",
  },
  {
    id: 13,
    name: "Honey-crem",
    category: "Cosmetics",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 31.85,
    newPrice: 28.55,
    onSale: true,
    image: "/images/honey-crem.jpg",
  },
  {
    id: 14,
    name: "Face mask",
    category: "Cosmetics",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 29.66,
    newPrice: 27.13,
    onSale: false,
    image: "/images/honey-face-mask.jpg",
  },
  {
    id: 15,
    name: "Honey facial mask",
    category: "Cosmetics",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 32.23,
    newPrice: 30.99,
    onSale: false,
    image: "/images/honey-facial-mask.jpg",
  },
  {
    id: 16,
    name: "Manuka honeycomb",
    category: "Other",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 30.31,
    newPrice: 25.55,
    onSale: true,
    image: "/images/honeycomb3.jpg",
  },
  {
    id: 17,
    name: "Pollen 500g",
    category: "Pollen",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 150.17,
    newPrice: 145.88,
    onSale: false,
    image: "/images/pollen2.jpg",
  },
  {
    id: 18,
    name: "Fiary mead",
    category: "Mead",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 170.86,
    newPrice: 160.11,
    onSale: true,
    image: "/images/Fiary-mead.jpg",
  },
  {
    id: 19,
    name: "Gosnells mead",
    category: "Mead",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 110.15,
    newPrice: 83.62,
    onSale: false,
    image: "/images/Gosnells-mead.jpg",
  },
  {
    id: 20,
    name: "Homemade mead",
    category: "Mead",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 190.28,
    newPrice: 153.13,
    onSale: false,
    image: "/images/Homemade-mead.jpg",
  },
  {
    id: 21,
    name: "Honey scrub",
    category: "Cosmetics",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 84.69,
    newPrice: 78.66,
    onSale: false,
    image: "/images/honey-scrub.jpg",
  },
  {
    id: 22,
    name: "Honey tree candle",
    category: "Candles",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 14.51,
    newPrice: 12.79,
    onSale: false,
    image: "/images/candle2.jpg",
  },
  {
    id: 23,
    name: "Honey heart candle",
    category: "Candles",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 15.12,
    newPrice: 13.91,
    onSale: true,
    image: "/images/candle3.jpg",
  },
  {
    id: 24,
    name: "Honey hive candle",
    category: "Candles",
    isLimited: false,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 17.72,
    newPrice: 15.44,
    onSale: false,
    image: "/images/candle4.jpg",
  },
  {
    id: 25,
    name: "Honey duo candle",
    category: "Candles",
    isLimited: true,
    description:
      "Our product is a natural honey, which is obtained from the flowers of various plants using traditional beekeeping methods. We guarantee the high quality of honey, because we do not use chemical additives or processing processes that can degrade the quality and usefulness of honey. Our honey is a source of vitamins and minerals as well as energy for your body. Try our natural honey and enjoy the real taste and benefits of nature!",
    price: 13.12,
    newPrice: 10.12,
    onSale: false,
    image: "/images/candle5.jpg",
  },
];

export default products;
